version: '2'

networks:
  app-network:
    name: app-network

services:
  postgres:
    image: postgres:14.4-alpine3.16
    networks:
      - app-network
    environment:
      POSTGRES_DB: postgres        # Database name
      POSTGRES_USER: admin         # User for the database
      POSTGRES_PASSWORD: password  # Password for the user
      PGDATA: /var/lib/postgresql/data/pgdata  # Persistent data location
    ports:
      - 5432:5432  # Expose port for PostgreSQL
    container_name: local_postgres

  flask_app:
    build: ./src
    networks:
      - app-network
    ports:
      - 5000:5000  # Expose port for Flask API
    environment:
      DATABASE_URL: postgresql://admin:password@localhost:5432/postgres
    depends_on:
      - postgres
    container_name: flask_app
